[package]
name = "risc0-circuit-rv32im-sys"
description = "Generated HAL code for rv32im cicuit"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
links = "risc0-circuit-rv32im-sys"

[dependencies]
risc0-core = { workspace = true }

# [target.'cfg(not(target_os = "zkvm"))'.dependencies]
# risc0-sys = { workspace = true }

[build-dependencies]
# cc = "1.0"
glob = "0.3"
risc0-build-kernel = { workspace = true }

[features]
default = []
cuda = []
metal = []
